### ISSUE TITLE
Castle DB cannot be opened on macOS catalina

### ISSUE THREAD

**Issue by FabianMk** [ncannasse/castle#109]
I downloaded the castledb-1.5-osx.zip
When I try to open the CastleDB app I get the modal from the OS saying "The application "CastleDB" can't be opened"

I am running macOS 10.15.2.
The other installation methods also failed. 

What can I do to run CastleDB? 
<img width="420" alt="Screen Shot 2020-01-08 at 18 54 19" src="https://user-images.githubusercontent.com/8279995/71976379-c4dbe180-3248-11ea-983c-b0ff60265004.png">

**Comment by gamefish** [comment]
same here

**Comment by ncannasse** [comment]
You might need to upgrade to nwjs 64 bits

**Comment by gamefish** [comment]
Thank you! I can open the 1.5 .nw package with latest nwjs, but can not open app in castledb-1.5-osx.zip for mac

**Comment by vickylance** [comment]
How to fix this issue?

**Comment by pererikbergman** [comment]
Same here.

**Comment by guifes** [comment]
Same here. Then I downloaded nwjs and threw it inside package.nw decompressed folder. Managed to run it on OSX, but loading tileset or image files does not seem to be working properly.

**Comment by vickylance** [comment]
1) go to this site https://nwjs.io/downloads/  and download 64 bit mac os version (normal version).
2) Extract that and open nwjs.app its package Contents.
3) go to http://castledb.org/ and download OSX castle db
4) Open Castledb.app package contents.
5) Copy everything from Resources folder of castledb.app's Contents to nwjs.app's Contents/Resource folder.
6) Open that nwjs.app as a normal app it should open castledb.app

@pererikbergman @guifes  ^^

**Comment by guifes** [comment]
> 1. go to this site https://nwjs.io/downloads/  and download 64 bit mac os version (normal version).
> 2. Extract that and open nwjs.app its package Contents.
> 3. go to http://castledb.org/ and download OSX castle db
> 4. Open Castledb.app package contents.
> 5. Copy everything from Resources folder of castledb.app's Contents to nwjs.app's Contents/Resource folder.
> 6. Open that nwjs.app as a normal app it should open castledb.app
> 
> @pererikbergman @guifes ^^

I did it, and it still doesn't work. The program runs, but when I load the sample from the website, images do not appear. And I can enter edit mode on tilemaps.

**Comment by pererikbergman** [comment]
> 1. go to this site https://nwjs.io/downloads/  and download 64 bit mac os version (normal version).
> 2. Extract that and open nwjs.app its package Contents.
> 3. go to http://castledb.org/ and download OSX castle db
> 4. Open Castledb.app package contents.
> 5. Copy everything from Resources folder of castledb.app's Contents to nwjs.app's Contents/Resource folder.
> 6. Open that nwjs.app as a normal app it should open castledb.app
> 
> @pererikbergman @guifes ^^

Hey, thanks it works. But this is a very bad user experience :)

**Comment by ZacharyDK** [comment]
I got it to work on Mac. Video that helped me. https://www.youtube.com/watch?v=vlKgvaUAEeU

1. In the castleDB app, Show Contents, go to MacOS folder, rename to nw. (Is named to nwjs by default.)
2. in NWJS app, show package contents. Got to MacOS folder, drag in file renamed to nw.
3. Copy the resources from the CastleDB App to NWJS App. 
4. Run the app.

**Comment by mempler** [comment]
Still broken, however, its an permission issue, `+x` is just missing.
To fix it, just run following commands:

```sh
chmod +x '/Applications/CastleDB.app/Contents/MacOS/nwjs'
chmod +x '/Applications/CastleDB.app/Contents/Frameworks/nwjs Helper EH.app/Contents/MacOS/nwjs Helper EH'
chmod +x '/Applications/CastleDB.app/Contents/Frameworks/nwjs Helper NP.app/Contents/MacOS/nwjs Helper NP'
chmod +x '/Applications/CastleDB.app/Contents/Frameworks/nwjs Helper.app/Contents/MacOS/nwjs Helper'
chmod +x '/Applications/CastleDB.app/Contents/Frameworks/nwjs Framework.framework/nwjs Framework'
chmod +x '/Applications/CastleDB.app/Contents/Frameworks/crash_inspector'
```

Its less hacky than creating a whole new `.app`
