### ISSUE TITLE
Question: merging cdb files

### ISSUE THREAD

**Issue by KnightNine** [ncannasse/castle#110]
I needed to merge a number of cbd files but there doesn't seem to be any feature for that.

So I ended up pasting the sheets from my other cbd files into a central one using a JSON script editor and it worked but I can no longer move sheets left or right without the editor throwing errors and the sheets breaking. I'm guessing it's because that functionality was dependent on the indentation of the data which I messed up in the process of editing the file. Is there a way I can fix this?

ty.

**Comment by ncannasse** [comment]
Indentation is not important. If you correctly append the "sheets" content
of the two cdbs it should work ok unless you have some duplicate sheet
name, in which case you should rename before merging.

Le dim. 26 janv. 2020 à 09:17, KnightNine <notifications@github.com> a
écrit :

**Comment by KnightNine** [comment]
I can't identify what I have done wrong in the process of appending the sheet. I just tested it again to confirm that it was me editing the file that causes this issue compared to just creating a new sheet in the cbd editor itself, seems to consistently have this issue when I merge two of my filled files together.

I then tried it with empty sheets the same way as my full sheets and it worked fine! So what i was doing is correct but I am at a loss for why it causes this strange issue with the filled sheets. The file would have to be identical regardless of the data being entered using the cdb editor or otherwise, so this could me an issue with the data I've entered?

I don't mind sharing this unfinished database if you want to test this issue with moving the sheets left/right yourself. 

This is the error i am getting when i shift the sheets left or right:
![Capture](https://user-images.githubusercontent.com/34152090/73133641-939d3880-3fe0-11ea-850b-d3fc2c455d18.PNG)

And here's a database I edited that throws this error.

`{
	"sheets": [
		{
			"name": "Character",
			"columns": [
				{
					"typeStr": "1",
					"name": "Name",
					"display": null
				},
				{
					"typeStr": "1",
					"name": "Race",
					"display": null
				},
				{
					"typeStr": "8",
					"name": "Consumable Status Maximum Modifiers"
				},
				{
					"typeStr": "8",
					"name": "Status Modifiers"
				},
				{
					"typeStr": "8",
					"name": "Attached Actions",
					"display": null
				},
				{
					"typeStr": "8",
					"name": "Passive Abilities"
				},
				{
					"typeStr": "8",
					"name": "Skill"
				},
				{
					"typeStr": "8",
					"name": "Items & Trinkets"
				},
				{
					"typeStr": "8",
					"name": "Armor"
				},
				{
					"typeStr": "1",
					"name": "Model Params",
					"display": null
				}
			],
			"lines": [
				{
					"Name": "Hound",
					"Attached Actions": [],
					"Skill": [
						{
							"Physical": 0,
							"Derivation": 0,
							"Manipulation": 0,
							"Alteration": 0,
							"Reversion": 0,
							"Conjuration": 0,
							"Void": 0
						}
					],
					"Passive Abilities": [],
					"Model Params": "",
					"Status Modifiers": [
						{
							"Speed": 0,
							"Stealth": 0,
							"Perception Range": 0,
							"Perception Field of View": 0,
							"Memory": 0,
							"Carry Capacity": 0,
							"Resistances & Weaknesses": []
						}
					],
					"Consumable Status Maximum Modifiers": [
						{
							"Health": 0,
							"Energy": 0
						}
					],
					"Armor": [],
					"Items & Trinkets": [],
					"Race": "Hound"
				}
			],
			"separators": [],
			"props": {}
		},
		{
			"name": "Character@Consumable Status Maximum Modifiers",
			"props": {
				"hide": true
			},
			"separators": [],
			"lines": [],
			"columns": [
				{
					"typeStr": "3",
					"name": "Health",
					"display": null
				},
				{
					"typeStr": "3",
					"name": "Energy",
					"display": null
				}
			]
		},
		{
			"name": "Character@Attached Actions",
			"props": {
				"hide": true
			},
			"separators": [],
			"lines": [],
			"columns": [
				{
					"typeStr": "1",
					"name": "Action Name",
					"display": null
				}
			]
		},
		{
			"name": "Character@Status Modifiers",
			"props": {
				"hide": true
			},
			"separators": [],
			"lines": [],
			"columns": [
				{
					"typeStr": "3",
					"name": "Speed",
					"display": null
				},
				{
					"typeStr": "3",
					"name": "Stealth",
					"display": null
				},
				{
					"typeStr": "3",
					"name": "Perception Range",
					"display": null
				},
				{
					"typeStr": "3",
					"name": "Perception Field of View",
					"display": null
				},
				{
					"typeStr": "3",
					"name": "Memory",
					"display": null
				},
				{
					"typeStr": "3",
					"name": "Carry Capacity",
					"display": null
				},
				{
					"typeStr": "8",
					"name": "Resistances & Weaknesses",
					"display": null
				}
			]
		},
		{
			"name": "Character@Skill",
			"props": {
				"hide": true
			},
			"separators": [],
			"lines": [],
			"columns": [
				{
					"typeStr": "3",
					"name": "Physical",
					"display": null
				},
				{
					"typeStr": "3",
					"name": "Derivation",
					"display": null
				},
				{
					"typeStr": "3",
					"name": "Manipulation",
					"display": null
				},
				{
					"typeStr": "3",
					"name": "Alteration",
					"display": null
				},
				{
					"typeStr": "3",
					"name": "Reversion",
					"display": null
				},
				{
					"typeStr": "3",
					"name": "Conjuration",
					"display": null
				},
				{
					"typeStr": "3",
					"name": "Void",
					"display": null
				}
			]
		},
		{
			"name": "Character@Passive Abilities",
			"props": {
				"hide": true
			},
			"separators": [],
			"lines": [],
			"columns": [
				{
					"typeStr": "1",
					"name": "Passive Ability Name",
					"display": null
				},
				{
					"typeStr": "1",
					"name": "Params",
					"display": null
				}
			]
		},
		{
			"name": "Character@Items & Trinkets",
			"props": {
				"hide": true
			},
			"separators": [],
			"lines": [],
			"columns": [
				{
					"typeStr": "1",
					"name": "Item/Trinket Name"
				},
				{
					"typeStr": "3",
					"name": "Ammount",
					"display": null
				}
			]
		},
		{
			"name": "Character@Armor",
			"props": {
				"hide": true
			},
			"separators": [],
			"lines": [],
			"columns": [
				{
					"typeStr": "1",
					"name": "Headdress",
					"display": null
				},
				{
					"typeStr": "1",
					"name": "Garment"
				}
			]
		},
		{
			"name": "Character@Status Modifiers@Resistances & Weaknesses",
			"props": {
				"hide": true
			},
			"separators": [],
			"lines": [],
			"columns": [
				{
					"typeStr": "1",
					"name": "Source Effect Property Name"
				},
				{
					"typeStr": "3",
					"name": "Value",
					"display": null
				}
			]
		},
		{
			"name": "Action",
			"columns": [
				{
					"typeStr": "1",
					"name": "Category"
				},
				{
					"typeStr": "0",
					"name": "Name"
				},
				{
					"typeStr": "8",
					"name": "Range"
				},
				{
					"typeStr": "8",
					"name": "Effect"
				},
				{
					"typeStr": "8",
					"name": "Cost",
					"display": null
				},
				{
					"typeStr": "8",
					"name": "Targeting",
					"display": null
				},
				{
					"typeStr": "1",
					"name": "Animation Params",
					"display": null
				}
			],
			"lines": [
				{
					"Name": "Move",
					"Effect": [
						{
							"Function Name": "MoveActorToTarget",
							"Additional Params": "[]"
						}
					],
					"Cost": [
						{
							"Consumable Status": "Time",
							"Value": 1,
							"Cost Mechanics": [
								{
									"Mechanic Name": "ScaleCostByDistanceFromActor",
									"Params": "[1]"
								},
								{
									"Mechanic Name": "DivideCostByStatus",
									"Params": "[0.5,Speed]"
								},
								{
									"Mechanic Name": "IncreaseCostByMissingConsumableStatusBelowPercentage",
									"Params": "[0.5,Health,\"<\",50]"
								}
							],
							"Minimum Cost": 1
						}
					],
					"Category": "Physical",
					"Range": [
						{
							"Minimum Range": 0,
							"Maximum Range": -1,
							"Range Mechanics": []
						}
					],
					"Targeting": [
						{
							"Minimum Targets": 1,
							"Maximum Targets": 1,
							"Targeting Mechanics": []
						}
					],
					"Animation Params": ""
				},
				{
					"Category": "Physical",
					"Name": "Slap",
					"Range": [
						{
							"Minimum Range": 1,
							"Maximum Range": 1,
							"Range Mechanics": []
						}
					],
					"Effect": [
						{
							"Function Name": "ApplyDamageToTarget",
							"Additional Params": "[1,Physical]"
						}
					],
					"Cost": [
						{
							"Consumable Status": "Time",
							"Value": 1,
							"Cost Mechanics": [],
							"Minimum Cost": 1
						}
					],
					"Targeting": [
						{
							"Minimum Targets": 1,
							"Maximum Targets": 1,
							"Targeting Mechanics": [
								{
									"Mechanic Name": "LineOfSightRequirement",
									"Params": "[]"
								}
							]
						}
					],
					"Animation Params": ""
				}
			],
			"separators": [],
			"props": {}
		},
		{
			"name": "Action@Effect",
			"props": {
				"hide": true
			},
			"separators": [],
			"lines": [],
			"columns": [
				{
					"typeStr": "1",
					"name": "Function Name"
				},
				{
					"typeStr": "1",
					"name": "Additional Params"
				}
			]
		},
		{
			"name": "Action@Effect@StatReliance",
			"props": {
				"hide": true
			},
			"separators": [],
			"lines": [],
			"columns": [
				{
					"typeStr": "0",
					"name": "Stats",
					"display": null
				},
				{
					"typeStr": "4",
					"name": "Multiplier",
					"display": null
				}
			]
		},
		{
			"name": "Action@Cost",
			"props": {
				"hide": true
			},
			"separators": [],
			"lines": [],
			"columns": [
				{
					"typeStr": "1",
					"name": "Consumable Status"
				},
				{
					"typeStr": "3",
					"name": "Value"
				},
				{
					"typeStr": "3",
					"name": "Minimum Cost",
					"display": null
				},
				{
					"typeStr": "8",
					"name": "Cost Mechanics"
				}
			]
		},
		{
			"name": "Action@Cost@Cost Mechanics",
			"props": {
				"hide": true
			},
			"separators": [],
			"lines": [],
			"columns": [
				{
					"typeStr": "1",
					"name": "Mechanic Name",
					"display": null
				},
				{
					"typeStr": "1",
					"name": "Params",
					"display": null
				}
			]
		},
		{
			"name": "Action@Range",
			"props": {
				"hide": true
			},
			"separators": [],
			"lines": [],
			"columns": [
				{
					"typeStr": "3",
					"name": "Minimum Range"
				},
				{
					"typeStr": "3",
					"name": "Maximum Range",
					"display": null
				},
				{
					"typeStr": "8",
					"name": "Range Mechanics",
					"display": null
				}
			]
		},
		{
			"name": "Action@Range@Range Mechanics",
			"props": {
				"hide": true
			},
			"separators": [],
			"lines": [],
			"columns": [
				{
					"typeStr": "1",
					"name": "Mechanic Name",
					"display": null
				},
				{
					"typeStr": "1",
					"name": "Params",
					"display": null
				}
			]
		},
		{
			"name": "Action@Targeting",
			"props": {
				"hide": true
			},
			"separators": [],
			"lines": [],
			"columns": [
				{
					"typeStr": "3",
					"name": "Minimum Targets",
					"display": null
				},
				{
					"typeStr": "3",
					"name": "Maximum Targets",
					"display": null
				},
				{
					"typeStr": "8",
					"name": "Targeting Mechanics",
					"display": null
				}
			]
		},
		{
			"name": "Action@Targeting@Targeting Mechanics",
			"props": {
				"hide": true
			},
			"separators": [],
			"lines": [],
			"columns": [
				{
					"typeStr": "1",
					"name": "Mechanic Name",
					"display": null
				},
				{
					"typeStr": "1",
					"name": "Params",
					"display": null
				}
			]
		}
	],
	"customTypes": [],
	"compress": false
}`

**Comment by Epono** [comment]
For what's it's worth, I pasted your data (formatted or not) in a .cdb file and got no error while moving sheets left or right.

Maybe it's an encoding issue caused by the manual pasting in a text editor?

**Comment by KnightNine** [comment]
I do not believe so if it works fine when I paste empty sheets with the same method, or does the size of what is being pasted cause this issue? Well at least now I know that it's just me. I'll try something that isn't notepad to manually edit the csd files, maybe that'll fix it. 

![issue](https://user-images.githubusercontent.com/34152090/73134309-fcd57980-3fe9-11ea-8632-b4710a224110.gif)

**Comment by KnightNine** [comment]
Seems to have fixed itself.
