### ISSUE TITLE
Heaps.io Inspector not working

### ISSUE THREAD

**Issue by alexpana** [ncannasse/castle#111]
I'm creating a totally empty heaps.io project with build.hxml:

        -lib heaps
        -lib hxbit
        -lib hlsdl
        -lib castle
        -main Main
        -D windowTitle=Hello World!
        -hl game.hl
        -debug

And an empty app, except for the inspector.

The error I see in the castledb inspector is 

        Uncaught Error: 17 is not a valid enum constructor 

        indexcastle.js:8385 Type.createEnumIndex
        castle.js:9177 cdb_BinSerializer.unserializeSchema
        castle.js:8840 cdb_BinSerializer.doUnserialize
        castle.js:523 (anonymous function)
        events.js:75 emitOne
        events.js:150 emit
        _stream_readable.js:146 readableAddChunk
        _stream_readable.js:109 Readable.push
        net.js:510 onread

I'm using haxe 4.0.5, heaps.io 1.7.0 and castledb 1.5 release.

**Comment by ncannasse** [comment]
You might need a GIT build of castledb client.

**Comment by alexpana** [comment]
Thank you very much for your reply.

I already tried a git build, but that unfortunately didn't even show the inspector tab. The release downloaded from the official landing page shows "???" as the inspector tab, but I can't activate it. The git build from master doesn't show any tab at all. The git build also shows a warning:

        lz4.js:81 Linking failure in asm.js: Invalid heap size

Is the inspector supposed to work? The `JqPages.hx` which I assume is the inspector implementation hasn't be changed in the last two years.

**Comment by alexpana** [comment]
I managed to trace to issue to the `JqPages#updateTabs()` function not adding the tabs to the sheets panel. I have no idea why it doesn't work (the `appendTo` has no effect), but I changed the `NW.js` framework to the SDK release (to get inspector access) and it magically worked.

If you have any ideas, I'd love to hear your thoughts on this, either way I'm stoked it works!
