### ISSUE TITLE
Python wrapper?

### ISSUE THREAD

**Issue by eranimo** [ncannasse/castle#20]
Python got the Enum class in Python 3.4. It would be nice if we could have a wrapper for Castle-format JSON files into enums.

**Comment by ncannasse** [comment]
I'm not sure I understand what you want here ? Do you want to use CastleDB and Haxe/Python, or use CastleDB JSON output from within a Python native app ? How are enums related ? (CastleDB use its own format for enums storage)

**Comment by eranimo** [comment]
The second option. It would be nice to have an adapter to use Castle enums in Python. I'm not familiar with Haxe, but it would be better to have a Python native implementation to integrate into existing applications.

**Comment by ncannasse** [comment]
@eranimo what about using Haxe/Python to generate all the necessary classes then importing into your python project ? Haxe CDB support uses a lot of macros and I'm not familiar with Python metaprogramming capacities.

**Comment by ncannasse** [comment]
I'm closing for now, unless you want to contribute one I have not enough knowledge in Python to provide it myself.
