### ISSUE TITLE
Undocumented dependencies?

### ISSUE THREAD

**Issue by JSandusky** [ncannasse/castle#24]
Are all dependencies documented? Running into issues compiling on windows particularly with jquery and node-webkit imports.

Example offendesr:
```
import js.jquery.Helper.*;
import js.node.webkit.MenuItem;
```
From history tracking that appears to have been from hxnodejs from which it was removed?

JQuery was easy enough to handle just manually merging head against an older commit.

**Comment by ncannasse** [comment]
I was part of hxnodejs but then removed, it is now directly part of CDB here:
https://github.com/ncannasse/castle/tree/master/src/js/node/webkit

**Comment by ncannasse** [comment]
for JQuery you need latest GIT/Haxe

**Comment by JSandusky** [comment]
Thanks! Didn't look like there was anywhere else to ask or I would have instead of "raising an issue."
