### ISSUE TITLE
How to get object of type created in CastleDB

### ISSUE THREAD

**Issue by jaqjacek** [ncannasse/castle#25]
I'v created db file with simple sheet named pon with vars:  "x , y , type , timestamp"
Can I create a new object of type pon inside code ? 
   var testPon = new DB.Pon();
after that line i'v get error :  Pon does not have a constructor

**Comment by ncannasse** [comment]
CastleDB is a static database, it means you cannot insert objects into it at runtime in your code. It has been created to input static data such as monsters stats, items, etc. in games.
