### ISSUE TITLE
Missing shortcuts documentation

### ISSUE THREAD

**Issue by Northburns** [ncannasse/castle#26]
I'm currently working on a CastleDB file with 10 sheets (with more to come). When resizing the window's width down, the last sheets (most to the right) become inaccessible.

Maybe a "jump to a sheet" action, or key shortcuts for moving to previous/next sheet, would be neat?

**Comment by ncannasse** [comment]
You can already use Ctrl+Tab and Shift+Ctrl+Tab to move between sheets.

**Comment by Northburns** [comment]
Neat! castledb.org should be updated to include that, right? Should it be an issue in this repo or some other?

**Comment by ncannasse** [comment]
Right, we don't have a list of shortcuts for CDB, I've edited your issue title.

**Comment by afaur** [comment]
Please review https://github.com/ncannasse/castle/pull/28 to let me know if that is the best place for this information.

**Comment by awreese** [comment]
FYI, this update isn't currently reflected on castledb.org.
