### ISSUE TITLE
Modifying column, pressing enter deletes column

### ISSUE THREAD

**Issue by Northburns** [ncannasse/castle#34]
I've now tripped over this one too many times :smile: 

Scenario: I have a sheet with many columns, with at least a couple of enumeration columns, and while filling my sheet, I find myself adding new values to the enumeration as I discover more applicable values.

If I edit the column, enter a new enum value, and _press enter_, the _Delete column_ action is then taken, instead of the _Modify column_ one. 

I feel like the default action when modifying a column should be "Modify". Better yet, some confirmation on column deletion would be really cool.

**Comment by ncannasse** [comment]
The Delete button has been removed in GIT version ;)

**Comment by Northburns** [comment]
Oh that's nice :+1: I'll evaluate if I am patient enough to wait for a release or if I'll start running the snapshot version :)
