### ISSUE TITLE
how get method paramterInfo value in C#

### ISSUE THREAD

**Issue by dannylili** [ncannasse/castle#40]
var _stackTrace = new StackTrace();
            var frame = _stackTrace.GetFrame(0);
            var _method = frame.GetMethod();
            var _arguments = _method.GetParameters();
            var strBuder = new StringBuilder();
            for (int i = 0; i < _arguments.Length; i++)
            {
                var param = _arguments[i];
                if (param.ParameterType.IsClass)
                {

                    strBuder.Append(JsonConvert.SerializeObject(param.RawDefaultValue));
                }
          }

regardness

**Comment by ncannasse** [comment]
Sorry but I have no idea from your issue whereas it's even related to CastleDB.

**Comment by dannylili** [comment]
Thank you,I asked the topic is irrelevant for CastleDB,just want to know C#  syntax to do it.

Regardness
