### ISSUE TITLE
Missing menu bar

### ISSUE THREAD

**Issue by IkonOne** [ncannasse/castle#46]
Hi,

I downloaded the latest version of CastleDB from the website and I cannot save because there is no menu bar.  Maybe I misunderstand how to use it?  The rest of the functionality seems to work well.

OS: OSX El Capitan
OS Version: 10.11.6

![screen shot 2016-10-05 at 9 42 26 am](https://cloud.githubusercontent.com/assets/1105646/19115676/e133ed4a-8ae0-11e6-9891-31cc3b139c9d.png)

**Comment by ncannasse** [comment]
Seems like a problem with NWJS. On OSX Menu bar should be at the very top of the screen, is it not present here?

**Comment by IkonOne** [comment]
Ahh.  It is.  The menu is labeed as nwjs so I never clicked it to check...  Thank you.

![screen shot 2016-10-05 at 11 34 11 am](https://cloud.githubusercontent.com/assets/1105646/19120039/a9f0306e-8aef-11e6-9a2d-912b58dc4459.png)
