### ISSUE TITLE
Feature Request: Quads and Fonts for Map Editor?

### ISSUE THREAD

**Issue by Justinfront** [ncannasse/castle#47]
For application development the Map editor could be potentially useful but it does not seems to have any ability to position Quads with perhaps 1 or 4 colors, or TextFields with custom fonts. Also it would be nice to have Place holders where component would be inserted later.  

Curious if this is a direction that would be suitable for castleDB.

In regard to Applications how would you approach dynamic castleDB where json differences could be transfered by say Haxe remoting and applied in real time or does this not seem sensible?

**Comment by ncannasse** [comment]
I don't think that using CDB Level Editor for UI development is a good idea, it has not been designed at all in this mind and would like too many feature, they are too many different workflows.

**Comment by Justinfront** [comment]
Ok fair enough, but would have thought quads would be useful for game backgrounds, and I would assume that some onscreen text might want to be placed in the level editor.  I suppose this is aimed at the tile approach, but gl systems often like quads as well as images.
