### ISSUE TITLE
Linux, could not load image

### ISSUE THREAD

**Issue by starburst997** [ncannasse/castle#48]
None of the images would load under linux, to make it works I had to add "file://" at the beginning of the URL.

Simple fix I did was to add the "file://" under the getAbsPath function in Model.hx.

Not sure if this would affect things under win/mac. But just pointing that out for anyone else having the same issue.

**Comment by ncannasse** [comment]
Could you confirm it works now?

**Comment by starburst997** [comment]
Yup, works perfectly!
