### ISSUE TITLE
Error while adding a new line to the list column

### ISSUE THREAD

**Issue by dkolyesnik** [ncannasse/castle#52]
`castle.js:11162 Uncaught TypeError: Cannot read property 'getDefault' of null
    at data_Sheet.newLine (castle.js:11162)
    at Main.newLine (castle.js:6541)
    at Main.insertLine (castle.js:6547)
    at <anonymous>:1:3`

It looks like the sheet's that are created for the list columns has field "base" equals null for some reason

**Comment by dkolyesnik** [comment]
Field "base" is null because this sheets are created with null passed instead of the database.
I guess there was a reason behind this, but for now I can't understand it. And field base is required to display default values of the fields.
@ncannasse  can you please fix this or give some feedback on why null is passed so I could fix it without worrying to break something else

**Comment by ncannasse** [comment]
Thanks for the report, I did a lot of refactoring recently but didn't fully test. Don't hesitate to report if you have other issues.
