### ISSUE TITLE
Deleting a sheet bug

### ISSUE THREAD

**Issue by dkolyesnik** [ncannasse/castle#53]
Deleting a sheet do not delete if from the database, so it is still exists after reloading.
A quick fix for me was adding 
`getSheetData()`
 method to Sheet class and 
` data.sheets.remove(sheet.getSheetData());`
to the method deleteSheet in Database, but there might be a better way.

**Comment by R32** [comment]
move sheet to Left/Right also does not work.

**Comment by ChrisTeister** [comment]
The fix descripbed by dkolyesnik works.

You can fix the move sheet bug by adding these lines in popupSheet() in Main.hx
```
base.data.sheets.remove(s.sheet);
base.data.sheets.insert(prev, s.sheet);
```

You also have to make the data field public in Database.hx

The reason for both bugs is, that the underlying database isn't updated, but only the data used for visual representation.
