### ISSUE TITLE
Missing API Documentation?

### ISSUE THREAD

**Issue by awreese** [ncannasse/castle#59]
First off, awesome work!  I have everything up an running and can access my db within haxe... but now I'm wondering how else I can access my game data.  So far I've seen that I can do the following:
- `[DB].[sheet].get([field]).[...]`
- `[DB].[sheet].resolve(["field"]).[...]`
- `[DB].[sheet].all[index].[...]`

I've searched through this repo and googled extenisvely, but haven't turned up much.  Is this basically the API or are there other ways to query my data?  Thanks.

**Comment by ncannasse** [comment]
Yes that's pretty much all of it. Since all data is in memory, you can use this to access all of it.

**Comment by awreese** [comment]
Thanks for the quick response.  I don't mean to be pedantic here, but when you say it's "pretty much all of it", are there still other accessors available, or are those the only ones available?

**Comment by ncannasse** [comment]
Yes that's all of it.
