### ISSUE TITLE
Cannot parametrize enum argument as SheetName

### ISSUE THREAD

**Issue by nikitaosyak** [ncannasse/castle#60]
Hello.

Doc says, 
"A custom type constructor parameter can use the following types:
SheetName any sheet name created in the database"

So I want to use a following custom type: 

`enum TemplateType {
	Reference( v: SheetName );
}`

And getting error: 'Unknown type SheetName'

what am i doing wrong?

**Comment by ncannasse** [comment]
You need to set the sheet name, for instance  v : level if your sheet is named "level"

**Comment by nikitaosyak** [comment]
So I only can parametrize with specific sheet name? I see. I thought I could use SheetName type and parametrize it with specific sheet in every other table cell.

**Comment by ncannasse** [comment]
No, you can't use generics in castledb enums
