### ISSUE TITLE
No eraser in Map Editor ?

### ISSUE THREAD

**Issue by Epono** [ncannasse/castle#63]
Let me juste preface this issue with my love for everything you've created.

Now, my question.

Is there a way to remove a tile or an object from a layer in the Map Editor ? I looked a bit in the source but didn't find any, but it seems too important a feature to be missing.

**Comment by ncannasse** [comment]
The "Del" key on PC keyboard works.

On Fri, Mar 23, 2018 at 4:53 PM, Guillaume Ambrois <notifications@github.com

**Comment by Epono** [comment]
Thanks! I feel stupid now :)

In my defence though, it's missing from the list of shortcuts.
