### ISSUE TITLE
Can't decode [Data.sheetName.all] array

### ISSUE THREAD

**Issue by Epono** [ncannasse/castle#67]
Doc states:
> **Data Layer** ` cbd.Types.Layer<SheetName>` : you can decode the layer by passing the `Data.sheetName.all` array to the `decode()` function.

Which `decode()` function is it? The [`Layer<T>(String)`](https://github.com/ncannasse/castle/blob/master/cdb/Types.hx#L120) one or the [`TileLayerData(String)`](https://github.com/ncannasse/castle/blob/master/cdb/Types.hx#L140) one? And how should I access it? 

Neither my `Data` object, nor `Data.sheetName.all` have a `decode()` function and the types I tried in the `cdb.Types` class only have `encode()` functions, not `decode()`

PS: for the record, I know how to decode layers individually with the following code, but I understood there was another way.
```
for (layer in Data.levelDatas.get(LevelDatasKind.FirstVillage).layers) {
	trace("name : " + layer.name);
	trace("file : " + layer.data.file);
	trace("size : " + layer.data.size);
	trace("stride : " + layer.data.stride);
	trace("data : " + layer.data.data.decode());
}
```

**Comment by ncannasse** [comment]
I think it's now done directly without arguments by calling  data.decode()
as your example shows.

On Mon, Mar 26, 2018 at 5:13 PM, Guillaume Ambrois <notifications@github.com
