### ISSUE TITLE
problems following source compilation instructions

### ISSUE THREAD

**Issue by increpare** [ncannasse/castle#74]
```Download and copy NWJS from http://nwjs.io into the /bin/nwjs directory```

`/bin` is a system protected directory on macOS now, I can't add stuff there even if I want to.  Or do you mean the local subdirectory of the project? In this case I'd say `bin/nwjs` and not have the first slash (that normally means global path on linux/osx, right?).

Also, when I download `nwjs` from the site I get an `nwjs.app` bundle, not a single binary.  I copied the bundle to `bin/nwjs/nwjs.app`, ran `haxe castle.hxml`, but running it afterwards, it was still just the regular container app.

Copying `nwjs.app` directly to `bin/nwjs.app` and running `haxe castle.hxml` results in it launching and then closing before it can even open a window.  (Not sure where to look for log files tbh. Not sure why it only crashes in that particular directory - I can move it to other directories and it's just fine.).

**Comment by ncannasse** [comment]
Thanks for the report and sorry for the delay, I have updated OSX instructions for NWJS packaging, please try again.

**Comment by increpare** [comment]
works. ty! :)
