### ISSUE TITLE
exporting to gdevelop

### ISSUE THREAD

**Issue by raMASTER** [ncannasse/castle#75]
trying to create a database that can be used on gdevelop which uses a tree structure to store variables.
guessing i need a new parser file where:

castledb columns, lines, values would be gdevelop grandparent node, parent node, child node

castledb:
"name": "column1"
				}
			],
			"lines": [
				{
					"column1": "line1"
				}
		
gdevelop:
variable name="column1">
            children>
                variable name="line1">
                    children>
                        variable name="value1" value="0" />

**Comment by ncannasse** [comment]
I don't think we should support directly exporters in CDB, given anyone can write a script that easily manipulates the CDB JSON output.
