### ISSUE TITLE
Improve build instructions

### ISSUE THREAD

**Issue by chanon** [ncannasse/castle#78]
I tried to build CastleDB myself and found the instructions could be improved so people don't have to figure out too much themselves.

Some things missing from build instructions:
- That castle also requires hxbit package to be installed (otherwise you will get error about `vdom.Server`)
- That the output hxnodejs js file should be named `castle.js`
- An example command line for actually building `castle.js`

Here is example updated documentation for this:

#### 1. Install Prerequisites
- Install [Haxe](https://haxe.org) using approriate installer from https://haxe.org/download/
- Install [hxnodejs](https://github.com/HaxeFoundation/hxnodejs) using the command `haxelib install hxnodejs`
- Install [hxbit](https://github.com/ncannasse/hxbit) using the command `haxelib install hxbit`

#### 2. Build castle.js
- Clone this repository
- At the root of the repository folder run
```haxe -lib hxbit -lib hxnodejs -cp src -main Main.hx -js bin/castle.js```
- This will create `castle.js` file in the `bin` folder
(BTW I think maybe there should be a build script for this.)

#### 3. Package or Run with NWJS
- Download and copy NWJS from http://nwjs.io into the bin/nwjs directory
- Run cdb.cmd on windows or nwjs/nwjs from bin directory on Linux
- On OSX, you need to copy all bin files into bin/nwjs.app/Contents/Resources/app.nw folder, then open the NWJS application

Enjoy!

---

I think this would help people to more easily build CastleDB from source and thus contribute with pull requests

**Comment by chanon** [comment]
Raw markdown of above in-case you want to use it:

```
### Compile from sources:

#### 1. Install Prerequisites
- Install [Haxe](https://haxe.org) using approriate installer from https://haxe.org/download/
- Install [hxnodejs](https://github.com/HaxeFoundation/hxnodejs) using the command `haxelib install hxnodejs`
- Install [hxbit](https://github.com/ncannasse/hxbit) using the command `haxelib install hxbit`

#### 2. Build castle.js
- Clone this repository
- At the root of the repository folder run
```haxe -lib hxbit -lib hxnodejs -cp src -main Main.hx -js bin/castle.js```
- This will create `castle.js` file in the `bin` folder

#### 3. Package or Run with NWJS
- Download and copy NWJS from http://nwjs.io into the bin/nwjs directory
- Run cdb.cmd on windows or nwjs/nwjs from bin directory on Linux
- On OSX, you need to copy all bin files into bin/nwjs.app/Contents/Resources/app.nw folder, then open the NWJS application

Enjoy!
```

**Comment by ncannasse** [comment]
Thanks, I've updated the README.md, next time you can make a PR against it if you want ;)
