### ISSUE TITLE
Completion server invalidates CDB generated module cache

### ISSUE THREAD

**Issue by kiroukou** [ncannasse/castle#92]
Hello,
I'm having a problem with the completion on my project.
Everytimes a completion request is sent to the server, I'm having the CDB build call (and so, the types generation).

I'm testing with haxe RC2, castle haxe lib from git.
I'm using VSCode with the haxe plugin, here is the output of the call in verbose mode (a bit cleaned): 
```
Processing Arguments [--cwd,d:/Projects/PROJECT/client,display.hxml,-D,display-details,--no-output,--display,{"jsonrpc":"2.0","id":11,"method":"display/completion","params":{"file":"d:/Projects/PROJECT/client/src/pr/Level.hx","contents":blablabla
Defines castle=1.5.0,dce=no,debug=1,display-details=1,display=1,display_details=1,display_stdin=1,format=3.4.2,haxe3=1,haxe4=1,haxe_ver=4.000,heaps=1.5.0,heaps_sprite=1,hl=1,hlopenal=1.4.0,hlsdl=1.8.0,hxbit=1.4.1,source-header=Generated by Haxe 4.0.0-rc.2+77068e10c,static=1,sys=1,target.name=hl,target.static=true,target.sys=true,target.threaded=true,target.utf16=true,true=1,utf16=1
Using signature 64e8a933cf4e3f442e94857b125c41c6
Display position: d:\projects\PROJECT\client\src\pr\level.hx: 4061-4061
 0, hl: skipping pr.Level
 0, hl: parsed d:\projects\PROJECT\client\src\pr\level.hx (not cached, is display file)
 0, hl: skipping Types(pr.Level)
 0, hl: skipping Data(pr.Level)
.....

Stats = 1 files, 348 classes, 1 methods, 142 macros
Time spent : 1.632s
Haxe print:
C:\haxeTools\lib\castle/git/cdb/Module.hx:101: BUILD CDB

Processing Arguments [--cwd,d:/Projects/PROJECT/client,display.hxml,-D,display-details,--no-output,--display,{"jsonrpc":"2.0","id":12,"method":"display/completionItem/resolve","params":{"index":0}}]
Stats = 0 files, 0 classes, 0 methods, 0 macros
Time spent : 0.000s
```

The trace output in Module.hx is a trace I've put at the begin of the build method.

Any idea ?

**Comment by ncannasse** [comment]
Seems like your Data module references Types which references your Level.hx
Make sure your Data module has no dependency to gameplay code.

**Comment by kiroukou** [comment]
Not sure to understand the log as you do.
from what I can read, there Data AND Types referened in pr.Level.
The completion request being in pr.Level, both are skipped.

In the code I have as dependencies : 
Types > uses Data macro generated Type
Level > uses Data and Types

But Data itself does not seem to have any dependency.  No customType or anything like that.
