### ISSUE TITLE
[Feature Request] SQL-like Query Engine for CastleDB

### ISSUE THREAD

**Issue by dimumurray** [ncannasse/castle#96]
As per [Heaps.io discourse topic](https://community.heaps.io/t/sql-like-query-engine-for-castledb/312):

> Here's a crazy idea.
> 
> What if there was a database query engine available, where we could leverage SQL-like commands to perform CRUD(Create,Read,Update,Delete) operations, in-game, on a CastleDB database?
> 
> Is there an open-source library that allows for this? If not, are there any plans to make one?

**Comment by ncannasse** [comment]
I actually started a long time ago to look at implementing a backend for Haxe record-macros (https://lib.haxe.org/p/record-macros/) to CDB, that involved parsing SQL. But it's not a fun work to do, with actually very little advantage over for instance using SQLite.

CDB is meant to be some kind of read-only database, authoring is only done off-game.

**Comment by dimumurray** [comment]
Didn't realize SQLite was an option (found the [sys.db.SQLite](https://api.haxe.org/sys/db/Sqlite.html) class thanks to your tip)! Thank you so much for that information. Would you be open to adding an SQLite file export option to CastleDB?

I've found CastleDB to be great for mocking up data models for a custom Entity Component System(ECS). It allows me to rapidly test different ideas with respect to ECS architecture (far easier to work with when compared to database GUI editors such as MySQLWorkbench or Navicat). The plan is to store entity/component definitions in a flat file database and leverage CRUD operations as part of the game update loop. Does that sound like a bad idea?
