### ISSUE TITLE
JSON Parser Error with Haxe 4.0 RC3

### ISSUE THREAD

**Issue by JarduDray** [ncannasse/castle#97]
I'm testing the Development version of Haxe and ran into this error while trying to load my cdb file as per the instructions:

Invalid char 114 at position 0
Called from haxe.format.JsonParser.invalidChar (/home/jardu/haxe/std/haxe/format/JsonParser.hx line 291)
Called from haxe.format.JsonParser.parseRec (/home/jardu/haxe/std/haxe/format/JsonParser.hx line 147)
Called from haxe.format.JsonParser.doParse (/home/jardu/haxe/std/haxe/format/JsonParser.hx line 57)
Called from cdb.$Parser.parse (cdb/Parser.hx line 57)
Called from sTV.cdb.$ArenaDB.load (cdb/Module.hx line 514)
Called from sTV.locales.$Arena.__constructor__ (sTV/locales/Arena.hx line 28)
Called from sTV.screen.$MainGameScreen.__constructor__ (sTV/screen/MainGameScreen.hx line 28)
Called from sTV.$Game.__constructor__ (sTV/Game.hx line 12)
Called from Main.init (Main.hx line 8)
Called from hxd.App.~setup.2 (hxd/App.hx line 124)
Called from hxd.App.loadAssets (hxd/App.hx line 152)
Called from hxd.App.setup (hxd/App.hx line 122)
Called from h3d.Engine.onCreate (h3d/Engine.hx line 243)
Called from h3d.impl.GlDriver.~init.0 (h3d/impl/GlDriver.hx line 1548)
Called from haxe.$Timer.~delay.0 (/home/jardu/haxe/std/haxe/Timer.hx line 140)
Called from haxe.$Timer.~__constructor__.0 (/home/jardu/haxe/std/haxe/Timer.hx line 74)
Called from haxe.$MainLoop.tick (/home/jardu/haxe/std/haxe/MainLoop.hx line 166)
Called from hxd.$System.runMainLoop (hxd/System.hl.hx line 124)
Called from haxe.$Timer.~delay.0 (/home/jardu/haxe/std/haxe/Timer.hx line 140)
Called from haxe.$Timer.~__constructor__.0 (/home/jardu/haxe/std/haxe/Timer.hx line 74)
Called from haxe.$MainLoop.tick (/home/jardu/haxe/std/haxe/MainLoop.hx line 166)
Called from haxe.$EntryPoint.processEvents (/home/jardu/haxe/std/haxe/EntryPoint.hx line 99)
Called from haxe.$EntryPoint.run (/home/jardu/haxe/std/haxe/EntryPoint.hx line 125)
Job 2, 'hl bin/game.hl' has stopped

**Comment by ncannasse** [comment]
Seems like your json starts with a `r` letter which is not valid JSON
